// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASY5bFDsTvN7NZlhcDfVT4ZJdZf_8V55Y',
    appId: '1:794874749792:web:aa8b4d72c5bcf71558b405',
    messagingSenderId: '794874749792',
    projectId: 'parking-system-b85fa',
    authDomain: 'parking-system-b85fa.firebaseapp.com',
    storageBucket: 'parking-system-b85fa.firebasestorage.app',
    measurementId: 'G-X0XJ3KDVTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5czCPtisGG8_T4OvAWq_L46cSSBpMWw',
    appId: '1:794874749792:android:2456e78ef33dc86258b405',
    messagingSenderId: '794874749792',
    projectId: 'parking-system-b85fa',
    storageBucket: 'parking-system-b85fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABAQI2zFr16n1uiHlE1T3s6nH6SYVnec8',
    appId: '1:794874749792:ios:66549388de244b6458b405',
    messagingSenderId: '794874749792',
    projectId: 'parking-system-b85fa',
    storageBucket: 'parking-system-b85fa.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABAQI2zFr16n1uiHlE1T3s6nH6SYVnec8',
    appId: '1:794874749792:ios:66549388de244b6458b405',
    messagingSenderId: '794874749792',
    projectId: 'parking-system-b85fa',
    storageBucket: 'parking-system-b85fa.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASY5bFDsTvN7NZlhcDfVT4ZJdZf_8V55Y',
    appId: '1:794874749792:web:ff5cb781785b7b5058b405',
    messagingSenderId: '794874749792',
    projectId: 'parking-system-b85fa',
    authDomain: 'parking-system-b85fa.firebaseapp.com',
    storageBucket: 'parking-system-b85fa.firebasestorage.app',
    measurementId: 'G-K980SVR1L1',
  );
}
